# Generated by Django 5.2.8 on 2025-11-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesFamiliares',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('condicion', models.CharField(max_length=100)),
                ('presente', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'antecedentes_familiares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AntecedentesGinecologicos',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('embarazada', models.IntegerField(blank=True, null=True)),
                ('meses_embarazo', models.IntegerField(blank=True, null=True)),
                ('anticonceptivos', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'antecedentes_ginecologicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AntecedentesNoPatologicos',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('respira_boca', models.IntegerField(blank=True, null=True)),
                ('alimentos_citricos', models.IntegerField(blank=True, null=True)),
                ('muerde_unas', models.IntegerField(blank=True, null=True)),
                ('muerde_objetos', models.IntegerField(blank=True, null=True)),
                ('fuma', models.IntegerField(blank=True, null=True)),
                ('cantidad_cigarros', models.IntegerField(blank=True, null=True)),
                ('apretamiento_dentario', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'antecedentes_no_patologicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AntecedentesPatologicosPersonales',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('cirugia', models.IntegerField(blank=True, null=True)),
                ('medicamentos_actuales', models.IntegerField(blank=True, null=True)),
                ('tratamiento_medico', models.IntegerField(blank=True, null=True)),
                ('estado_salud', models.CharField(blank=True, max_length=7, null=True)),
                ('ultimo_examen', models.DateField(blank=True, null=True)),
                ('problemas_sanguineos', models.TextField(blank=True, null=True)),
                ('oncologicos', models.IntegerField(blank=True, null=True)),
                ('leucemia', models.IntegerField(blank=True, null=True)),
                ('problemas_renales', models.IntegerField(blank=True, null=True)),
                ('hemofilia', models.IntegerField(blank=True, null=True)),
                ('transfusion', models.IntegerField(blank=True, null=True)),
                ('deficit_vitamina_k', models.IntegerField(blank=True, null=True)),
                ('drogas', models.IntegerField(blank=True, null=True)),
                ('problemas_corazon', models.IntegerField(blank=True, null=True)),
                ('alergia_penicilina', models.IntegerField(blank=True, null=True)),
                ('alergia_anestesia', models.IntegerField(blank=True, null=True)),
                ('alergia_aspirina_yodo', models.IntegerField(blank=True, null=True)),
                ('hepatitis', models.IntegerField(blank=True, null=True)),
                ('fiebre_reumatica', models.IntegerField(blank=True, null=True)),
                ('asma', models.IntegerField(blank=True, null=True)),
                ('diabetes', models.IntegerField(blank=True, null=True)),
                ('ulcera_gastrica', models.IntegerField(blank=True, null=True)),
                ('tension_alta', models.IntegerField(blank=True, null=True)),
                ('tension_baja', models.IntegerField(blank=True, null=True)),
                ('enfermedades_venereas', models.IntegerField(blank=True, null=True)),
                ('herpes_aftas', models.IntegerField(blank=True, null=True)),
                ('vih', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'antecedentes_patologicos_personales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactosEmergencia',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'contactos_emergencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialesClinicos',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'historiales_clinicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeloPermisos',
            fields=[
                ('pk', models.CompositePrimaryKey('modelo_id', 'permiso_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'modelo_permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeloRoles',
            fields=[
                ('pk', models.CompositePrimaryKey('modelo_id', 'rol_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'modelo_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modelos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('ultima_consulta', models.DateField(blank=True, null=True)),
                ('motivo_ultima_consulta', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'pacientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolPermisos',
            fields=[
                ('pk', models.CompositePrimaryKey('rol_id', 'permiso_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rol_permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioRoles',
            fields=[
                ('pk', models.CompositePrimaryKey('usuario_id', 'rol_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.TextField()),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
