# Generated by Django 5.2.8 on 2025-11-21 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antecedentesfamiliares',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='antecedentesginecologicos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='antecedentesnopatologicos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='antecedentespatologicospersonales',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapi.historialesclinicos')),
            ],
            options={
                'db_table': 'antecedentes',
                'managed': True,
            },
        ),
    ]
