# Generated by Django 5.2.8 on 2025-11-21 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0002_alter_antecedentesfamiliares_options_and_more'),
    ]

    operations = [
        # Eliminar las tablas existentes de antecedentes
        migrations.RunSQL("DROP TABLE IF EXISTS antecedentes_familiares;"),
        migrations.RunSQL("DROP TABLE IF EXISTS antecedentes_ginecologicos;"),
        migrations.RunSQL("DROP TABLE IF EXISTS antecedentes_no_patologicos;"),
        migrations.RunSQL("DROP TABLE IF EXISTS antecedentes_patologicos_personales;"),
        migrations.RunSQL("DROP TABLE IF EXISTS antecedentes;"),
        
        # Recrear la tabla padre Antecedentes
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapi.HistorialesClinicos')),
                ('tipo', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'antecedentes',
                'managed': True,
            },
        ),
        
        # Recrear AntecedentesFamiliares con nueva estructura
        migrations.CreateModel(
            name='AntecedentesFamiliares',
            fields=[
                ('antecedente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coreapi.antecedentes')),
                ('alergia', models.BooleanField(default=False)),
                ('asma_bronquial', models.BooleanField(default=False)),
                ('cardiologicos', models.BooleanField(default=False)),
                ('oncologicos', models.BooleanField(default=False)),
                ('discrasias_sanguineas', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('hipertension_arterial', models.BooleanField(default=False)),
                ('renales', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'antecedentes_familiares',
                'managed': True,
            },
        ),
        
        # Recrear AntecedentesGinecologicos con nueva estructura
        migrations.CreateModel(
            name='AntecedentesGinecologicos',
            fields=[
                ('antecedente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coreapi.antecedentes')),
                ('embarazada', models.BooleanField(default=False)),
                ('meses_embarazo', models.IntegerField(blank=True, null=True)),
                ('anticonceptivos', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'antecedentes_ginecologicos',
                'managed': True,
            },
        ),
        
        # Recrear AntecedentesNoPatologicos con nueva estructura
        migrations.CreateModel(
            name='AntecedentesNoPatologicos',
            fields=[
                ('antecedente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coreapi.antecedentes')),
                ('respira_boca', models.BooleanField(default=False)),
                ('alimentos_citricos', models.BooleanField(default=False)),
                ('muerde_unas', models.BooleanField(default=False)),
                ('muerde_objetos', models.BooleanField(default=False)),
                ('fuma', models.BooleanField(default=False)),
                ('cantidad_cigarros', models.IntegerField(blank=True, null=True)),
                ('apretamiento_dentario', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'antecedentes_no_patologicos',
                'managed': True,
            },
        ),
        
        # Recrear AntecedentesPatologicosPersonales con nueva estructura completa
        migrations.CreateModel(
            name='AntecedentesPatologicosPersonales',
            fields=[
                ('antecedente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coreapi.antecedentes')),
                ('estado_salud', models.CharField(blank=True, choices=[('buena', 'Buena'), ('regular', 'Regular'), ('mala', 'Mala')], max_length=10, null=True)),
                ('fecha_ultimo_examen', models.DateField(blank=True, null=True)),
                ('bajo_tratamiento_medico', models.BooleanField(default=False)),
                ('toma_medicamentos', models.BooleanField(default=False)),
                ('intervencion_quirurgica', models.BooleanField(default=False)),
                ('sangra_excesivamente', models.BooleanField(default=False)),
                ('problema_sanguineo', models.BooleanField(default=False)),
                ('anemia', models.BooleanField(default=False)),
                ('problemas_oncologicos', models.BooleanField(default=False)),
                ('leucemia', models.BooleanField(default=False)),
                ('problemas_renales', models.BooleanField(default=False)),
                ('hemofilia', models.BooleanField(default=False)),
                ('transfusion_sanguinea', models.BooleanField(default=False)),
                ('deficit_vitamina_k', models.BooleanField(default=False)),
                ('consume_drogas', models.BooleanField(default=False)),
                ('problemas_corazon', models.BooleanField(default=False)),
                ('alergia_penicilina', models.BooleanField(default=False)),
                ('alergia_anestesia', models.BooleanField(default=False)),
                ('alergia_aspirina', models.BooleanField(default=False)),
                ('alergia_yodo', models.BooleanField(default=False)),
                ('alergia_otros', models.TextField(blank=True, null=True)),
                ('fiebre_reumatica', models.BooleanField(default=False)),
                ('asma', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('ulcera_gastrica', models.BooleanField(default=False)),
                ('tension_arterial', models.CharField(blank=True, choices=[('normal', 'Normal'), ('alta', 'Alta'), ('baja', 'Baja')], max_length=10, null=True)),
                ('herpes_aftas_recurrentes', models.BooleanField(default=False)),
                ('enfermedades_venereas', models.BooleanField(default=False)),
                ('vih_positivo', models.BooleanField(default=False)),
                ('otros', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'antecedentes_patologicos_personales',
                'managed': True,
            },
        ),
    ]
