# Generated by Django 5.2.8 on 2025-11-21 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0003_recreate_antecedentes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialesclinicos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pacientes',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='historial',
            field=models.ForeignKey(db_column='historial_id', on_delete=django.db.models.deletion.DO_NOTHING, to='coreapi.historialesclinicos'),
        ),
        migrations.AlterField(
            model_name='antecedentesfamiliares',
            name='antecedente',
            field=models.OneToOneField(db_column='antecedente_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coreapi.antecedentes'),
        ),
        migrations.AlterField(
            model_name='antecedentesginecologicos',
            name='antecedente',
            field=models.OneToOneField(db_column='antecedente_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coreapi.antecedentes'),
        ),
        migrations.AlterField(
            model_name='antecedentesnopatologicos',
            name='antecedente',
            field=models.OneToOneField(db_column='antecedente_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coreapi.antecedentes'),
        ),
        migrations.AlterField(
            model_name='antecedentespatologicospersonales',
            name='antecedente',
            field=models.OneToOneField(db_column='antecedente_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coreapi.antecedentes'),
        ),
    ]
