# Generated by Django 5.2.8 on 2025-11-25 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0004_alter_historialesclinicos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialesclinicos',
            name='paciente',
            field=models.ForeignKey(default='default-paciente', on_delete=django.db.models.deletion.CASCADE, to='coreapi.pacientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historialesclinicos',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
