# Generated by Django 5.2.8 on 2025-11-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0005_historialesclinicos_paciente_pacientes_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': True},
        ),
    ]
