# Generated by Django 5.2.8 on 2025-12-09 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0007_alter_contactosemergencia_options_usuarios_apellidos_and_more'),
    ]

    operations = [
        # Comentado porque ya existen en la BD
        # migrations.AddField(
        #     model_name='contactosemergencia',
        #     name='deleted_at',
        #     field=models.DateTimeField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='contactosemergencia',
        #     name='deleted_by',
        #     field=models.CharField(blank=True, max_length=100, null=True),
        # ),
        # migrations.AddField(
        #     model_name='contactosemergencia',
        #     name='is_deleted',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='contactosemergencia',
        #     name='paciente',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coreapi.pacientes'),
        # ),
        migrations.CreateModel(
            name='RegistroHistoriaClinica',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('materia', models.CharField(choices=[('periodoncia', 'Periodoncia'), ('cirugia', 'Cirugía'), ('endodoncia', 'Endodoncia'), ('operatoria', 'Operatoria'), ('prostodoncia_fija', 'Prostodoncia Fija'), ('prostodoncia_removible', 'Prostodoncia Removible'), ('odontopediatria', 'Odontopediatría'), ('ortodoncia', 'Ortodoncia')], db_index=True, help_text='Materia a la que pertenece este registro', max_length=50)),
                ('tipo_registro', models.CharField(choices=[('habitos', 'Hábitos'), ('antecedentes_periodontal', 'Antecedentes Periodontales'), ('examen_periodontal', 'Examen Periodontal'), ('periodontograma', 'Periodontograma'), ('evaluacion_oclusal', 'Evaluación Oclusal'), ('radiografia', 'Radiografía'), ('diagnostico', 'Diagnóstico'), ('plan_tratamiento', 'Plan de Tratamiento')], db_index=True, help_text='Tipo específico de registro (hábitos, periodontograma, etc.)', max_length=50)),
                ('datos', models.JSONField(blank=True, default=dict, help_text='Contenido del formulario en formato JSON')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones_docente', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('corregir', 'Necesita Correcciones')], db_index=True, default='pendiente', max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, db_column='aprobado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_aprobados', to='coreapi.usuarios')),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='registros_realizados', to='coreapi.usuarios')),
                ('historial', models.ForeignKey(db_column='historial_id', on_delete=django.db.models.deletion.CASCADE, related_name='registros_clinicos', to='coreapi.historialesclinicos')),
                ('paciente', models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.CASCADE, related_name='registros_clinicos', to='coreapi.pacientes')),
            ],
            options={
                'verbose_name': 'Registro de Historia Clínica',
                'verbose_name_plural': 'Registros de Historia Clínica',
                'db_table': 'registro_historia_clinica',
                'ordering': ['-fecha_registro'],
                'managed': True,
                'indexes': [models.Index(fields=['paciente', 'materia', 'tipo_registro'], name='idx_pac_mat_tipo'), models.Index(fields=['estudiante', 'estado', 'fecha_registro'], name='idx_est_estado_fecha'), models.Index(fields=['historial', '-fecha_registro'], name='idx_hist_fecha'), models.Index(fields=['materia', 'tipo_registro', 'estado'], name='idx_mat_tipo_estado')],
            },
        ),
    ]
