# Generated by Django 5.2.8 on 2025-12-09 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0008_contactosemergencia_deleted_at_and_more'),
    ]

    operations = [
        # Eliminar operaciones duplicadas de contactosemergencia ya que existen
        migrations.AlterField(
            model_name='registrohistoriaclinica',
            name='estudiante',
            field=models.ForeignKey(blank=True, db_column='estudiante_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_realizados', to='coreapi.usuarios'),
        ),
        migrations.AlterField(
            model_name='registrohistoriaclinica',
            name='historial',
            field=models.ForeignKey(blank=True, db_column='historial_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_clinicos', to='coreapi.historialesclinicos'),
        ),
    ]
