# Generated by Django 5.2.8 on 2025-12-12 17:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0009_contactosemergencia_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoPaciente',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_estudiante', to='coreapi.usuarios')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='coreapi.pacientes')),
            ],
            options={
                'db_table': 'seguimiento_paciente',
                'ordering': ['-fecha_creacion'],
                'managed': True,
                'unique_together': {('estudiante', 'paciente')},
            },
        ),
        migrations.CreateModel(
            name='EntradaSeguimiento',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('pieza_dental', models.CharField(max_length=10)),
                ('tratamiento', models.TextField()),
                ('nro_presupuesto', models.CharField(blank=True, max_length=50, null=True)),
                ('firmado', models.BooleanField(default=False)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('firmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_firmadas', to='coreapi.usuarios')),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='coreapi.seguimientopaciente')),
            ],
            options={
                'db_table': 'entrada_seguimiento',
                'ordering': ['-fecha', '-fecha_registro'],
                'managed': True,
            },
        ),
    ]
