# Generated by Django 5.2.8 on 2025-12-12 20:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0011_pacientes_ci'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocoloQuirurgico',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('diagnostico_preoperatorio', models.TextField()),
                ('diagnostico_postoperatorio', models.TextField()),
                ('cirujano', models.CharField(max_length=200)),
                ('anestesiologo', models.CharField(blank=True, max_length=200, null=True)),
                ('ayudantes', models.CharField(blank=True, max_length=300, null=True)),
                ('instrumentista', models.CharField(blank=True, max_length=200, null=True)),
                ('circulantes', models.CharField(blank=True, max_length=200, null=True)),
                ('tecnica_anestesia', models.CharField(blank=True, max_length=200, null=True)),
                ('duracion_cirugia', models.CharField(blank=True, max_length=100, null=True)),
                ('hallazgos_clinicos', models.TextField(blank=True, null=True)),
                ('hallazgos_radiograficos', models.TextField(blank=True, null=True)),
                ('hallazgos_laboratoriales', models.TextField(blank=True, null=True)),
                ('hallazgos_otros', models.TextField(blank=True, null=True)),
                ('descripcion_procedimiento', models.TextField()),
                ('hallazgos_quirurgicos', models.TextField(blank=True, null=True)),
                ('accidentes_quirurgicos', models.TextField(blank=True, null=True)),
                ('indicaciones_posquirurgicas', models.TextField(blank=True, null=True)),
                ('receta', models.TextField(blank=True, null=True)),
                ('fecha_cirugia', models.DateField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('docente', models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos_supervisados', to='coreapi.usuarios')),
                ('estudiante', models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.RESTRICT, related_name='protocolos_estudiante', to='coreapi.usuarios')),
                ('paciente', models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.RESTRICT, related_name='protocolos_quirurgicos', to='coreapi.pacientes')),
            ],
            options={
                'db_table': 'protocolo_quirurgico',
                'ordering': ['-fecha_cirugia', '-fecha_creacion'],
                'managed': True,
            },
        ),
    ]
