# Generated by Django 5.2.8 on 2025-12-12 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0013_permiso_contactosemergencia_deleted_at_and_more'),
        ('coreapi', '0013_permission_system'),
    ]

    operations = [
    ]
