# Generated by Django 5.2.8 on 2025-12-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0014_merge_20251212_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentesginecologicos',
            name='ciclo_menstrual',
            field=models.BooleanField(default=False),
        ),
    ]
