# Generated by Django 5.2.8 on 2025-12-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0015_antecedentesginecologicos_ciclo_menstrual'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentesginecologicos',
            name='edad_menopausia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentesginecologicos',
            name='fecha_ultima_menstruacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentesginecologicos',
            name='menopausia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentesginecologicos',
            name='terapia_hormonal',
            field=models.BooleanField(default=False),
        ),
    ]
