# Generated by Django 5.2.8 on 2025-12-14 20:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0016_antecedentesginecologicos_edad_menopausia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroperiodoncia',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]

