# Generated by Django 5.2.8 on 2025-12-15 05:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0018_citas_delete_registroperiodoncia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seguimientopaciente',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seguimientopaciente',
            name='materia_clinica',
            field=models.CharField(blank=True, choices=[('cirugia_bucal', 'Cirugía Bucal'), ('operatoria_endodoncia', 'Operatoria y Endodoncia'), ('periodoncia', 'Periodoncia'), ('prostodoncia_fija', 'Prostodoncia Fija'), ('prostodoncia_removible', 'Prostodoncia Removible'), ('odontopediatria', 'Odontopediatría'), ('semiologia', 'Semiología')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='TratamientoMateria',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('materia', models.CharField(choices=[('cirugia_bucal', 'Cirugía Bucal'), ('operatoria_endodoncia', 'Operatoria y Endodoncia'), ('periodoncia', 'Periodoncia'), ('prostodoncia_fija', 'Prostodoncia Fija'), ('prostodoncia_removible', 'Prostodoncia Removible'), ('odontopediatria', 'Odontopediatría'), ('semiologia', 'Semiología')], max_length=50)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('solicitado', 'Pendiente de Aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='borrador', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('observaciones_docente', models.TextField(blank=True, null=True)),
                ('cupo_numero', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('docente_revisor', models.ForeignKey(blank=True, db_column='docente_revisor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos_revisados', to='coreapi.usuarios')),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos_estudiante', to='coreapi.usuarios')),
                ('paciente', models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos_paciente', to='coreapi.pacientes')),
                ('seguimiento', models.ForeignKey(blank=True, db_column='seguimiento_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='coreapi.seguimientopaciente')),
            ],
            options={
                'verbose_name': 'Tratamiento de Materia',
                'verbose_name_plural': 'Tratamientos de Materias',
                'db_table': 'tratamiento_materia',
                'ordering': ['-creado_en'],
                'managed': True,
                'indexes': [models.Index(fields=['estudiante', 'materia'], name='tratamiento_estudia_3b6088_idx'), models.Index(fields=['estado'], name='tratamiento_estado_a8c87e_idx')],
            },
        ),
    ]
