# Generated by Django 5.2.8 on 2025-12-16 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0020_plantratamiento_procedimientoplan_evolucionclinica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferenciapaciente',
            name='docente_autoriza',
        ),
        migrations.AddField(
            model_name='transferenciapaciente',
            name='docente_aprobador',
            field=models.ForeignKey(blank=True, db_column='docente_aprobador_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_aprobadas', to='coreapi.usuarios'),
        ),
        migrations.AddField(
            model_name='transferenciapaciente',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferenciapaciente',
            name='materia_destino',
            field=models.CharField(choices=[('cirugia_bucal', 'Cirugía Bucal'), ('operatoria_endodoncia', 'Operatoria y Endodoncia'), ('periodoncia', 'Periodoncia'), ('prostodoncia_fija', 'Prostodoncia Fija'), ('prostodoncia_removible', 'Prostodoncia Removible'), ('odontopediatria', 'Odontopediatría'), ('semiologia', 'Semiología')], default='operatoria', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferenciapaciente',
            name='materia_origen',
            field=models.CharField(choices=[('cirugia_bucal', 'Cirugía Bucal'), ('operatoria_endodoncia', 'Operatoria y Endodoncia'), ('periodoncia', 'Periodoncia'), ('prostodoncia_fija', 'Prostodoncia Fija'), ('prostodoncia_removible', 'Prostodoncia Removible'), ('odontopediatria', 'Odontopediatría'), ('semiologia', 'Semiología')], default='operatoria', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transferenciapaciente',
            name='estado',
            field=models.CharField(choices=[('solicitada', 'Solicitada'), ('aprobada', 'Aprobada'), ('asignada', 'Asignada a Estudiante'), ('rechazada', 'Rechazada')], default='solicitada', max_length=20),
        ),
        migrations.AlterField(
            model_name='transferenciapaciente',
            name='estudiante_destino',
            field=models.ForeignKey(blank=True, db_column='estudiante_destino_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='coreapi.usuarios'),
        ),
        migrations.AlterField(
            model_name='transferenciapaciente',
            name='motivo',
            field=models.CharField(choices=[('graduacion', 'Graduación del Estudiante'), ('cambio_grupo', 'Cambio de Grupo'), ('abandono_estudiante', 'Abandono del Estudiante'), ('solicitud_paciente', 'Solicitud del Paciente'), ('requiere_especialidad', 'Requiere Otra Especialidad'), ('otro', 'Otro')], max_length=50),
        ),
    ]
