# Generated by Django 5.2.8 on 2025-12-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0021_remove_transferenciapaciente_docente_autoriza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaseguimiento',
            name='referencias_clinicas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='evolucionclinica',
            name='referencias_clinicas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
