# Generated by Django 5.2.8 on 2025-12-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0022_entradaseguimiento_referencias_clinicas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucionclinica',
            name='archivos_adjuntos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
