# Generated by Django 5.2.8 on 2025-12-16 05:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0023_evolucionclinica_archivos_adjuntos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupoEstudiante',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('materia', models.CharField(choices=[('cirugia_bucal', 'Cirugía Bucal'), ('operatoria_endodoncia', 'Operatoria y Endodoncia'), ('periodoncia', 'Periodoncia'), ('prostodoncia_fija', 'Prostodoncia Fija'), ('prostodoncia_removible', 'Prostodoncia Removible'), ('odontopediatria', 'Odontopediatría'), ('semiologia', 'Semiología')], max_length=50)),
                ('procedimientos_completados', models.IntegerField(default=0)),
                ('ultimo_procedimiento_fecha', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='cupos', to='coreapi.usuarios')),
            ],
            options={
                'verbose_name': 'Cupo de Estudiante',
                'verbose_name_plural': 'Cupos de Estudiantes',
                'db_table': 'cupo_estudiante',
                'ordering': ['estudiante', 'materia'],
                'managed': True,
                'unique_together': {('estudiante', 'materia')},
            },
        ),
    ]
